using G4.WebDriver.Models;

using System.Collections.Generic;

namespace G4.WebDriver.Remote
{
    /// <summary>
    /// Defines an interface for interacting with the logs generated by the WebDriver.
    /// </summary>
    public interface ILogManager
    {
        /// <summary>
        /// Retrieves the log entries of a specified type.
        /// </summary>
        /// <param name="type">The type of log to retrieve (e.g., "browser", "driver").</param>
        /// <returns>Returns an IEnumerable of LogEntryModel representing the log entries of the specified type.</returns>
        IEnumerable<LogEntryModel> GetLog(string type);
    }
}
